# Docs for Azure Web Apps Deploy: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ilostit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json

      - name: Install dependencies and build
        working-directory: ./backend
        run: |
          npm ci
          npm run build --if-present

      - name: Zip artifact for deployment
        working-directory: ./backend
        run: zip -r ../backend.zip . -x "node_modules/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write # Required for login with secrets

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          # Use your Azure credentials stored in GitHub secrets
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ilostit'
          slot-name: 'Production'
          package: backend.zip
          # --- FIX 1: Corrected startup command ---
          startup-command: 'node server.js'
          # --- FIX 2: Added app settings from secrets (Best Practice) ---
          # This automatically sets your environment variables in Azure.
          # You must create these secrets in your GitHub repository settings.
          app-settings-json: |
            [
                { "name": "SUPABASE_URL", "value": "${{ secrets.SUPABASE_URL }}", "slotSetting": false },
                { "name": "SUPABASE_ANON_KEY", "value": "${{ secrets.SUPABASE_ANON_KEY }}", "slotSetting": false },
                { "name": "GOOGLE_PERSPECTIVE_API_KEY", "value": "${{ secrets.GOOGLE_PERSPECTIVE_API_KEY }}", "slotSetting": false },
                { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true", "slotSetting": false }
            ]

