name: Build and deploy Node.js app to Azure Web App - ilostit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4  # Updated to latest version for better compatibility
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json  # Enable caching for faster builds

      - name: npm install and build
        working-directory: ./backend
        run: |
          npm ci  # Use ci for cleaner installs from package-lock.json
          npm run build --if-present

      - name: Zip backend for deployment
        working-directory: ./backend
        run: zip -r ../backend.zip .  # This zips contents at root, which is correct

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend.zip
          retention-days: 5  # Optional: Retain artifact for debugging

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for verification
        run: unzip backend.zip -d ./extracted  # Optional: Unzip to verify structure locally in workflow logs

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ilostit'
          slot-name: 'Production'
          package: ./backend.zip  # Deploy the zip directly
          startup-command: 'node dist/server.js'  # Optional: Customize if your entry point is not app.js/index.js (adjust as needed)