name: Build and deploy Node.js app to Azure Web App - ilostit

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and Build
        run: |
          cd backend
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip . -x "node_modules/*" -x "src/*" -x "test/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ILOSTIT }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ILOSTIT }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ILOSTIT }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET_ILOSTIT }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ilostit'
          slot-name: 'Production'
          package: '.'
