name: Build and deploy Node.js app to Azure Web App - ilostit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          npm install

      - name: Build (if needed)
        working-directory: ./backend
        run: |
          npm run build --if-present

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r backend/package*.json deploy/
          cp -r backend/node_modules deploy/
          cp backend/server.js deploy/
          # If you have other files (config, public, etc.), copy them too
          # cp -r backend/public deploy/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_729C6289EE8F4305BA306D677F509DFD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8B3DDF039A474783B4280461C1164F77 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F5D90908DD5A4A2C9D240B7B6B1675CD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ilostit'
          slot-name: 'Production'
          package: deploy/
