name: Build and deploy Node.js app to Azure Web App - ilostit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json

      - name: npm install and build
        working-directory: ./backend
        run: |
          npm ci
          npm run build --if-present  # If this fails, it will error the workflow now (remove --if-present if you confirm the script exists)

      - name: List directory for debugging
        working-directory: ./backend
        run: |
          ls -la  # Log root files
          ls -la dist || echo "No dist folder found"  # Check if dist exists post-build

      - name: Zip backend for deployment
        working-directory: ./backend
        run: zip -r ../backend.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend.zip
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip and list for verification
        run: |
          unzip backend.zip -d ./extracted
          ls -la ./extracted  # Log contents in workflow output for debugging
          ls -la ./extracted/dist || echo "No dist folder in zip"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ilostit'
          slot-name: 'Production'
          package: ./backend.zip
          startup-command: 'npm start'  # Change to this (assumes package.json has a "start" script like "node server.js"). If not, use 'node server.js' or your actual entry point.