name: Build and deploy Node.js app to Azure Web App - ilostit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install
        working-directory: ./backend
        run: npm install

      - name: Prepare deployment package
        run: |
          # Create a clean deployment folder
          mkdir -p deploy

          # Copy package files (skip if missing)
          cp backend/package.json deploy/ 2>/dev/null || true
          cp backend/package-lock.json deploy/ 2>/dev/null || true

          # Copy entry point JS files (skip if none)
          cp backend/*.js deploy/ 2>/dev/null || true

          # Copy runtime folders if they exist
          [ -d backend/routes ] && cp -r backend/routes deploy/
          [ -d backend/public ] && cp -r backend/public deploy/
          [ -d backend/views ] && cp -r backend/views deploy/

      - name: Zip deployment folder
        run: |
          cd deploy
          zip -r ../deploy.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ilostit'
          slot-name: 'Production'
          package: ./deploy.zip
